#!/usr/bin/env python3
# Purpose: OpenPGP seal/unseal for Agent Q outer blob (encrypt; optional sign via gpg).
# Created: 2026-03-09
# Last updated: 2026-03-09

"""
Seal: encrypt inner bytes to recipient pubkey -> single armored blob.
Unseal: decrypt with recipient private -> inner bytes.

Sign-then-encrypt in pure PGPy requires usage flags on generated keys. We support:
1) encrypt-only outer (inner JSON is still authenticated by promote rules if combined with ledger).
2) Keys generated by agentq key-gen set _require_usage_flags = False so encrypt/sign work in-process.

For production, prefer gpg-generated keys; fingerprint still maps in registry.
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path
from typing import Any

_ENGINE = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_ENGINE))
from lib.deps import require_deps  # noqa: E402

require_deps(["cryptography"])


class CryptoPipelineError(RuntimeError):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def _engine_crypto():
    skill_scripts = _ENGINE / "skills" / "localsetup-mail-protocol-control" / "scripts"
    sys.path.insert(0, str(skill_scripts))
    from crypto_engine import CryptoEngine  # type: ignore

    return CryptoEngine()


def seal_inner_json(manifest: dict[str, Any], recipient_pubkey_armored: str) -> str:
    """Encrypt canonical JSON manifest to recipient; return armored OpenPGP."""
    inner = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return seal_bytes(inner, recipient_pubkey_armored)


def seal_bytes(inner: bytes, recipient_pubkey_armored: str) -> str:
    eng = _engine_crypto()
    envelope = {
        "mode": "agentq_outer",
        "payload_b64": base64.b64encode(inner).decode("ascii"),
    }
    try:
        out = eng.encrypt_openpgp(envelope, recipient_pubkey_armored)
    except Exception as exc:
        raise CryptoPipelineError("ENCRYPT_FAILED", str(exc)) from exc
    armored = out.get("armored") or ""
    if not armored.strip():
        raise CryptoPipelineError("ENCRYPT_FAILED", "Empty armored output.")
    return armored if armored.strip().startswith("-----") else str(out)


def unseal_to_bytes(
    armored: str, recipient_private_armored: str, passphrase: str = ""
) -> bytes:
    """Decrypt armored blob; return inner bytes (JSON or raw)."""
    eng = _engine_crypto()
    if not armored.strip():
        raise CryptoPipelineError("DECRYPT_FAILED", "Empty armored input.")
    encrypted = {"mode": "openpgp", "armored": armored.strip()}
    try:
        envelope = eng.decrypt_openpgp(
            encrypted, recipient_private_armored, passphrase or ""
        )
    except Exception as exc:
        raise CryptoPipelineError("DECRYPT_FAILED", str(exc)) from exc
    if not isinstance(envelope, dict):
        raise CryptoPipelineError("DECRYPT_FAILED", "Decrypted payload not a dict.")
    if envelope.get("mode") == "agentq_outer" and envelope.get("payload_b64"):
        return base64.b64decode(str(envelope["payload_b64"]), validate=True)
    # Legacy: mail crypto stored JSON envelope as string inside message
    if "manifest_version" in envelope or "from_agent_id" in envelope:
        return json.dumps(envelope, sort_keys=True).encode("utf-8")
    raise CryptoPipelineError("DECRYPT_FAILED", "Not an agentq_outer envelope.")


def seal_bytes_strict_gpg(
    inner: bytes,
    recipient_pubkey_armored: str,
    signer_gnupghome: Path,
    signer_uid: str = "",
    passphrase: str = "",
) -> str:
    """Sign-then-encrypt outer per spec; requires gpg and signer GNUPGHOME."""
    from agentq_transport_client.gpg_crypto import gpg_sign_encrypt_armored

    return gpg_sign_encrypt_armored(
        inner,
        recipient_pubkey_armored=recipient_pubkey_armored,
        signer_gnupghome=Path(signer_gnupghome),
        signer_uid=signer_uid,
        passphrase=passphrase or "",
    )


def unseal_to_manifest_strict_gpg(
    armored: str,
    recipient_private_armored: str,
    passphrase: str,
    sender_pubkey_armored: str,
    recipient_gnupghome: Path | None = None,
) -> tuple[dict[str, Any], str]:
    """
    Decrypt+verify; plaintext must be JSON manifest.
    Returns (manifest, signer_fingerprint).
    """
    from agentq_transport_client.gpg_crypto import gpg_decrypt_verify_armored

    plain, signer_fp = gpg_decrypt_verify_armored(
        armored,
        recipient_sec_armored=recipient_private_armored,
        recipient_passphrase=passphrase or "",
        sender_pubkey_armored=sender_pubkey_armored,
        recipient_gnupghome=recipient_gnupghome,
    )
    m = json.loads(plain.decode("utf-8"))
    if not isinstance(m, dict):
        raise CryptoPipelineError("MANIFEST_PARSE_FAILED", "Strict gpg plaintext not object.")
    return m, signer_fp


def unseal_to_manifest(
    armored: str, recipient_private_armored: str, passphrase: str = ""
) -> dict[str, Any]:
    data = unseal_to_bytes(armored, recipient_private_armored, passphrase)
    try:
        m = json.loads(data.decode("utf-8"))
    except Exception as exc:
        raise CryptoPipelineError("MANIFEST_PARSE_FAILED", str(exc)) from exc
    if not isinstance(m, dict):
        raise CryptoPipelineError("MANIFEST_PARSE_FAILED", "Inner payload not an object.")
    return m


# Part 2 naming: single module entrypoints for agents reading the spec
def encrypt_then_sign(
    inner: bytes,
    recipient_pubkey_armored: str,
    signer_gnupghome: Path,
    signer_uid: str = "",
    passphrase: str = "",
) -> str:
    """Alias for seal_bytes_strict_gpg (sign-then-encrypt outer)."""
    return seal_bytes_strict_gpg(
        inner,
        recipient_pubkey_armored,
        signer_gnupghome,
        signer_uid=signer_uid,
        passphrase=passphrase,
    )


def verify_then_decrypt(
    armored: str, recipient_private_armored: str, passphrase: str = ""
) -> dict[str, Any]:
    """
    Decrypt-only path (PGPy agentq_outer). For strict gpg + signature binding use
    unseal_to_manifest_strict_gpg after decrypt-only first pass in ingest.
    """
    return unseal_to_manifest(armored, recipient_private_armored, passphrase)
